Entity/Event.php
<?php

/*
 * This file is part of the Claroline Connect package.
 *
 * (c) Claroline Consortium <consortium@claroline.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Claroline\AgendaBundle\Entity;

use Claroline\CoreBundle\Entity\Workspace\Workspace;
use Claroline\CoreBundle\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Claroline\AgendaBundle\Validator\Constraints\DateRange;

/**
 * @ORM\Entity(repositoryClass="Claroline\AgendaBundle\Repository\EventRepository")
 * @ORM\Table(name="claro_event")
 * @DateRange()
 */
class Event
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(length=50)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(name="start_date", type="integer", nullable=true)
     */
    private $start;

    /**
     * @ORM\Column(name="end_date", type="integer", nullable=true)
     */
    private $end;

    /**
     * @ORM\Column(nullable=true, type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(
     *     targetEntity="Claroline\CoreBundle\Entity\Workspace\Workspace",
     *     cascade={"persist"}
     * )
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $workspace;

    /**
     * @ORM\ManyToOne(targetEntity="Claroline\CoreBundle\Entity\User")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\Column(name="is_all_day", type="boolean")
     */
    private $allDay = false;

    /**
     * @ORM\Column(name="is_task", type="boolean")
     */
    private $isTask = false;

    /**
     * @ORM\Column(name="is_task_done", type="boolean")
     */
    private $isTaskDone = false;

     /**
     * @ORM\Column(nullable=true)
     */
    private $priority;

    /**
     * @ORM\OneToMany(targetEntity="Claroline\AgendaBundle\Entity\EventInvitation", mappedBy="event")
     * @ORM\JoinColumn(nullable=true)
     */
    private $eventInvitations = null;

    //If this parameter is set to false, NOBODY could modify the event. This parameter is useful for displaying an event of another bundle without possibility of modification.
    /**
     * @ORM\Column(name="is_editable", nullable=true, type="boolean")
     */
    private $isEditable;

    public function __construct()
    {
        $this->eventInvitations = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    //Returns a String for the DateTimePicker of the AgendaType
    public function getStart()
    {
        return date('d/m/Y H:i', $this->start);
    }

    public function getStartInTimestamp()
    {
        return $this->start;
    }

    public function getStartInDateTime()
    {
        return \Datetime::createFromFormat('U', $this->start);
    }

    public function setStart($start)
    {
        if (is_string($start)) {
            $dateFormat = $this->isAllDay() ? 'd/m/Y' : 'd/m/Y H:i';
            $dateTime = \DateTime::createFromFormat($dateFormat, $start);
            if (!$dateTime) {
                $this->start = null;
            } else {
                $this->start = $dateTime->getTimestamp();
            }
        } elseif (is_int($start)) {
            $this->start = $start;
        } elseif ($start instanceof \DateTime) {
            $this->start = $start->getTimestamp();
        } else {
            throw new \Exception('Date format is not supported');
        }

        return $this;
    }

    //Returns a String for the DateTimePicker of the AgendaType
    public function getEnd()
    {
        return date('d/m/Y H:i', $this->end);
    }

    public function getEndInTimestamp()
    {
        return $this->end;
    }

    public function getEndInDateTime()
    {
        return \Datetime::createFromFormat('U', $this->end);
    }

    public function setEnd($end)
    {
        if (is_string($end)) {
            $dateFormat = $this->isAllDay() ? 'd/m/Y' : 'd/m/Y H:i';
            $dateTime = \DateTime::createFromFormat($dateFormat, $end);
            if (!$dateTime) {
                $this->end = null;
            } else {
                $this->end = $dateTime->getTimestamp();
            }
        } elseif (is_int($end)) {
            $this->end = $end;
        } elseif ($end instanceof \DateTime) {
            $this->end = $end->getTimestamp();
        } else {
            throw new \Exception('Date format is not supported');
        }

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function getWorkspace()
    {
        return $this->workspace;
    }

    public function setWorkspace($workspace = null)
    {
        $this->workspace = $workspace;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser(User $user)
    {
        $this->user = $user;
    }

    public function isAllDay()
    {
        return $this->allDay;
    }

    public function setIsAllDay($isAllDay)
    {
        $this->allDay = (bool) $isAllDay;
    }

    public function getPriority()
    {
        return $this->priority;
    }

    public function setPriority($priority)
    {
        $this->priority = $priority;
    }

    public function setIsTask($isTask)
    {
        $this->isTask = $isTask;
    }

    public function getIsTask()
    {
        return $this->isTask;
    }

    public function isTask()
    {
        return $this->isTask;
    }

    public function setIsTaskDone($isTaskDone)
    {
        $this->isTaskDone = $isTaskDone;

        return $this;
    }

    public function isTaskDone()
    {
        return $this->isTaskDone;
    }

    public function setIsEditable($isEditable)
    {
        $this->isEditable = $isEditable;

        return $this;
    }

    public function isEditable()
    {
        return $this->isEditable;
    }

    /**
     * Set allDay
     *
     * @param boolean $allDay
     *
     * @return Event
     */
    public function setAllDay($allDay)
    {
        $this->allDay = $allDay;

        return $this;
    }

    /**
     * Get allDay
     *
     * @return boolean
     */
    public function getAllDay()
    {
        return $this->allDay;
    }

    /**
     * Get isTaskDone
     *
     * @return boolean
     */
    public function getIsTaskDone()
    {
        return $this->isTaskDone;
    }

    /**
     * Get isEditable
     *
     * @return boolean
     */
    public function getIsEditable()
    {
        return $this->isEditable;
    }

    /**
     * Add eventInvitation
     *
     * @param \Claroline\AgendaBundle\Entity\EventInvitation $eventInvitation
     *
     * @return Event
     */
    public function addEventInvitation(\Claroline\AgendaBundle\Entity\EventInvitation $eventInvitation)
    {
        $this->eventInvitations[] = $eventInvitation;

        return $this;
    }

    /**
     * Remove eventInvitation
     *
     * @param \Claroline\AgendaBundle\Entity\EventInvitation $eventInvitation
     */
    public function removeEventInvitation(\Claroline\AgendaBundle\Entity\EventInvitation $eventInvitation)
    {
        $this->eventInvitations->removeElement($eventInvitation);
    }

    /**
     * Get eventInvitations
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEventInvitations()
    {
        return $this->eventInvitations;
    }

    public function jsonSerialize(User $user = null)
    {
        $guests = [];
        $invitation = null;
        foreach ($this->getEventInvitations() as $eventInvitation) {
            $guests[] = [
                'user_name' => $eventInvitation->getUser()->getUserName(),
                'status' => $eventInvitation->getStatus()
            ];

            if ($eventInvitation->getUser() === $user) {
                $invitation = $eventInvitation;
            }
        }

        return [
            'id' => $this->getId(),
            'title' => $invitation && !is_null($invitation->getTitle()) ? $invitation->getTitle() : $this->getTitle(),
            'start' => \Datetime::createFromFormat('U', $this->start)->format(\DateTime::ISO8601),
            'end' => \Datetime::createFromFormat('U', $this->end)->format(\DateTime::ISO8601),
            'color' => $this->getPriority(),
            'allDay' => $this->isAllDay(),
            'isTask' => $this->isTask(),
            'isTaskDone' => $this->isTaskDone(),
            'owner' => $this->getUser()->getUsername(),
            'description' =>  $invitation && !is_null($invitation->getDescription()) ? $invitation->getDescription() : $this->getDescription(),
            'workspace_id' => $this->getWorkspace() ? $this->getWorkspace()->getId() : null,
            'workspace_name' => $this->getWorkspace() ? $this->getWorkspace()->getName() : null,
            'className' => 'event_' . $this->getId(),
            'isEditable' => $this->isEditable() !== false && !$invitation,
            'durationEditable' => !$this->isTask() && $this->isEditable() !== false && !$invitation, // If it's a task, disable resizing
            'invitations' => $guests,
            'is_guest' => !is_null($invitation),
            'event_invitation_status' => [
                'ignore' => EventInvitation::IGNORE,
                'join' => EventInvitation::JOIN,
                'maybe' => EventInvitation::MAYBE,
                'resign' => EventInvitation::RESIGN,

Form/AgendaType.php
<?php

/*
 * This file is part of the Claroline Connect package.
 *
 * (c) Claroline Consortium <consortium@claroline.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Claroline\AgendaBundle\Form;

use Claroline\CoreBundle\Entity\User;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Form\AbstractType;
use Claroline\CoreBundle\Entity\Workspace\Workspace;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Translation\TranslatorInterface;
use JMS\DiExtraBundle\Annotation as DI;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @DI\Service("claroline.form.agenda")
 */
class AgendaType extends AbstractType
{
    private $translator;
    private $om;
    private $tokenStorage;
    private $isDesktop;
    private $guestMode;
    private $creationMode;

    /**
     * @DI\InjectParams({
     *     "translator"   = @DI\Inject("translator"),
     *     "om"           = @DI\Inject("claroline.persistence.object_manager"),
     *     "tokenStorage" = @DI\Inject("security.token_storage")
     * })
     */
    public function __construct(TranslatorInterface $translator, ObjectManager $om, TokenStorageInterface $tokenStorage)
    {
        $this->translator = $translator;
        $this->om = $om;
        $this->tokenStorage = $tokenStorage;
        $this->isDesktop = false;
        $this->creationMode = false;
        $this->guestMode = false;
    }

    public function setIsDesktop()
    {
        $this->isDesktop = true;
    }

    public function setGuestMode()
    {
        $this->guestMode = true;
    }

    public function setCreationMode()
    {
        $this->creationMode = true;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', [
                'label' => 'form.title',
                'required' => true
            ])
        ;

        if (!$this->guestMode) {
            $builder
                ->add('isTask', 'checkbox', array(
                    'label' => 'form.task',
                    'required' => false,
                    'attr' => array(
                        'data-target' => '#recurrenceButton',
                        'aria-expanded' => "true",
                        'aria-controls' => 'recurrenceButton'
                    )
                ))
                ->add('isAllDay', 'checkbox', array(
                    'label' => 'form.all_day',
                    'required' => false
                ))
                ->add('start', 'text', array(
                    'label' => 'form.start'
                ))
                ->add('end', 'text', array(
                    'label' => 'form.end'
                ))
            ;
        }

        if ($this->isDesktop && !$this->guestMode) {
            $builder->add('workspace', 'entity', [
                'label' => $this->translator->trans('workspace', [], 'platform'),
                'class' => 'Claroline\CoreBundle\Entity\Workspace\Workspace',
                'required' => false,
                'choices' => $this->getWorkspacesByUser(),
                'empty_value' => $this->translator->trans('desktop', [], 'platform'),
                'property' => 'name'
            ]);
        }

        $builder
            ->add('description', 'tinymce', [
                'label' => 'form.description'
            ])
        ;

        if (!$this->guestMode) {
            $builder
                ->add('priority', 'choice', [
                    'label' => 'form.priority',
                    'choices' => [
                        '#FF0000' => 'high',
                        '#01A9DB' => 'medium',
                        '#848484' => 'low'
                    ]
                ])

                ->add('users', 'userpicker', [
                    'label' => 'form.invitations',
                    'translation_domain' => 'agenda',
                    'multiple' => true,
                    'mapped' => false
                ])
            ;
        }

        if ($this->creationMode) {
            $builder->add(
                'recurrence',
                'choice',
                array(
                    'label' => 'form.recurrence',
                    'choices' => array(
                        'd' => 'time.day',
                        'od' => 'time.open_day',
                        'w' => 'time.week',
                        'tw' => 'time.two_weeks',
                        //uncomment this when the month recurrence is done
                        //'m' => 'time.month',
                        'y' => 'time.year'
                    ),
                    'multiple' => false,
                    'expanded' => true,
                    'mapped' => false
                )
            );
            $builder->add('endRecurrence', 'datepicker', array(
                'label' => 'form.end_recurrence',
                'mapped' => false
            ));
        }
    }

    public function getWorkspacesByUser()
    {
        return $this->om->getRepository('ClarolineAgendaBundle:Event')
            ->findEditableUserWorkspaces($this->tokenStorage->getToken()->getUser());
    }

    public function getName()
    {
        return 'agenda_form';
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'workspace' => new Workspace() ,
                'user' => new User(),
                'class' => 'Claroline\AgendaBundle\Entity\Event',
                'translation_domain' => 'agenda'
            )
        );
    }
}

Resources/views/Agenda/addEventModalForm.html.twig
<div id="modal-event-form" class="modal-dialog" role="dialog" aria-labelledby="agendaModalLabel" aria-hidden="true">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="agendaModalLabel"> {{ 'add_event'|trans({}, 'agenda') }}</h4>
        </div>
        <form method="post"
              action="{{ action }}"
              id="form-event" {{ form_enctype(form) }}
              role="form"
        >
            <div class="modal-body">
                {% if form.title is defined %} {{ form_row(form.title) }} {% endif %}
                {% if form.isTask is defined %} {{ form_row(form.isTask) }} {% endif %}
                {% if form.isAllDay is defined %} {{ form_row(form.isAllDay) }} {% endif %}
                {% if form.start is defined %} {{ form_row(form.start) }} {% endif %}
                {% if form.end is defined %} {{ form_row(form.end) }} {% endif %}
                {% if form.workspace is defined %} {{ form_row(form.workspace) }} {% endif %}
                {% if form.description is defined %} {{ form_row(form.description) }} {% endif %}
                {% if form.priority is defined %} {{ form_row(form.priority) }} {% endif %}
                {% if form.users is defined %} {{ form_row(form.users) }} {% endif %}
                <div class="collapse" id="reccurenceButton">
                    <input type="checkbox" data-toggle="collapse" data-target="#reccurenceData" aria-expanded="false" aria-controls="reccurenceData">
                        {{  'form.recurrence'|trans({}, 'agenda') }}
                    </input>
                    <div class="collapse" id="reccurenceData">
                        {% if form.recurrence is defined %} {{ form_row(form.recurrence) }} {% endif %}
                        {% if form.endRecurrence is defined %} {{ form_row(form.endRecurrence) }} {% endif %}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{{'cancel'|trans({}, 'agenda') }}</button>
                <button type="submit" class="btn btn-primary">{{ 'add_event'|trans({}, 'agenda') }}</button>
            </div>
        </form>
    </div>
</div>

Resources/views/Agenda/eventContent.html.twig
{% twig_js name="EventContent" %}

{% if event.isTask %}
    <div>{{ 'limit_date'|trans({}, 'agenda') }}: {{ event.end.string }}</div>
{% else %}
    <div>{{ 'form.start'|trans({}, 'agenda') }}: {{ event.start.string }}</div>
    <div>{{ 'form.end'|trans({}, 'agenda') }}: {{ event.end.string }}</div>
{% endif %}

<div>{{ 'form.author'|trans({}, 'agenda') }}: {{ event.owner }}</div>

<div>{{ 'workspace'|trans({}, 'platform') }}:
    {% if event.workspace_id is null %}
        {{ 'desktop'|trans({}, 'platform') }}
    {% else %}
        {{ event.workspace_name }}
    {% endif %}
</div>

{% if event.description is not empty %}
    {{ 'form.description'|trans({}, 'agenda') }} :
    <div style="max-height: 150px; overflow-y: auto;">
        {{ event.description|raw }}
    </div>
{% endif %}

{% if event.isTask  %}
    {% if event.isTaskDone%}
        <div style="background-color: darkgreen; color: #f5f5f5; text-align: center; padding: 5px 0;"><span class="fa fa-check-circle"></span> {{ 'task_done'|trans({}, 'agenda') }}</div>
    {% else %}
        <div style="background-color: darkred; color: #f5f5f5; text-align: center; padding: 5px 0;"><span class="fa fa-exclamation-circle"></span> {{ 'task_not_done'|trans({}, 'agenda') }}</div>
    {% endif %}
{% endif %}


{% if event.invitations|length > 0 %}
    {{ 'invitation_guests'|trans({}, 'agenda') }} :
    {% for invitation in event.invitations %}
        {% if invitation.status == event.event_invitation_status.ignore %}
            <span class="label label-default" title="{{ 'invitation_ignore'|trans({}, 'agenda') }}">{{ invitation.user_name }}</span>
        {% elseif invitation.status == event.event_invitation_status.join %}
            <span class="label label-success" title="{{ 'invitation_join'|trans({}, 'agenda') }}">{{ invitation.user_name }}</span>
        {% elseif invitation.status == event.event_invitation_status.maybe %}
            <span class="label label-primary" title="{{ 'invitation_maybe'|trans({}, 'agenda') }}">{{ invitation.user_name }}</span>
        {% elseif invitation.status == event.event_invitation_status.resign %}
            <span class="label label-danger" title="{{ 'invitation_resign'|trans({}, 'agenda') }}">{{ invitation.user_name }}</span>
        {% endif %}
    {% endfor %}
{% endif %}

{% if event.is_guest %}
    <div class="text-right" style="margin-top: 5px;">
        <a href="#" data-event-id="{{ event.id }}" class="modify-event-as-guest">{{ 'modify'|trans({}, 'agenda') }}</a>
    </div>
{% elseif event.editable %}
    <div class="text-right" style="margin-top: 5px;">
        <a href="#" data-event-id="{{ event.id }}" class="modify-event">{{ 'modify'|trans({}, 'agenda') }}</a>
    </div>
{% endif %}

Resources/views/Agenda/invitation.html.twig
{% extends 'ClarolineCoreBundle:Desktop:layout.html.twig' %}

{% block title %}
    {{ parent() ~ '' }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block breadcrumb %}
    {{
        macros.desktopBreadcrumbs([
            {
                'name': 'agenda'|trans({}, 'tools'),
                'href': path('claro_desktop_open_tool', {'toolName': 'agenda_'})
            },
            {
                'name': 'invitation'|trans({}, 'tools'),
                'href': ''
            }
        ])
    }}
{% endblock %}

{% block section_content %}
    <div class="panel-heading">
        <h3 class="panel-title">{{ 'invitation_to_an_event'|trans({}, 'agenda') }}</h3>
    </div>
    <div class="panel-body">
        {% if invitation is null %}
            <div class="alert alert-warning">
                {{ 'invitation_not_found'|trans({}, 'agenda') }}
            </div>
        {% elseif already_done %}
            <div class="alert alert-info">
                {{ 'invitation_already_done'|trans({}, 'agenda') }}
            </div>
        {% else %}
            {% if invitation.status == constant('Claroline\\AgendaBundle\\Entity\\EventInvitation::JOIN') %}
                <div class="alert alert-success">
                    {{ 'invitation_joined'|trans({}, 'agenda') }}
                </div>
            {% elseif invitation.status == constant('Claroline\\AgendaBundle\\Entity\\EventInvitation::MAYBE') %}
                <div class="alert alert-success">
                    {{ 'invitation_set_maybe'|trans({}, 'agenda') }}
                </div>
            {% elseif invitation.status == constant('Claroline\\AgendaBundle\\Entity\\EventInvitation::RESIGN') %}
                <div class="alert alert-success">
                    {{ 'invitation_canceled'|trans({}, 'agenda') }}
                </div>
            {% endif %}
        {% endif %}

        <a href="{{ path('claro_desktop_open_tool', {'toolName': 'agenda_'}) }}" class="btn btn-primary">{{ 'invitation_back_to_calendar'|trans({}, 'agenda') }}</a>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}

{% endblock javascripts %}

Resources/views/Agenda/updateEventModalForm.html.twig
<div id="modal-event-form" class="modal-dialog" role="dialog" aria-labelledby="agendaModalLabel" aria-hidden="true">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 id="agendaModalLabel"> {{ 'update_event'|trans({}, 'agenda') }}</h4>
        </div>
        <form method="post"
              action="{{ action }}"
              id="form-event" {{ form_enctype(form) }}
              role="form"
                >
            <div class="modal-body">
                {% if form.title is defined %} {{ form_row(form.title) }} {% endif %}
                {% if form.isTask is defined %} {{ form_row(form.isTask) }} {% endif %}
                {% if form.isAllDay is defined %} {{ form_row(form.isAllDay) }} {% endif %}
                {% if form.start is defined %} {{ form_row(form.start) }} {% endif %}
                {% if form.end is defined %} {{ form_row(form.end) }} {% endif %}
                {% if form.workspace is defined %} {{ form_row(form.workspace) }} {% endif %}
                {% if form.description is defined %} {{ form_row(form.description) }} {% endif %}
                {% if form.priority is defined %} {{ form_row(form.priority) }} {% endif %}
                {% if form.users is defined %} {{ form_row(form.users) }} {% endif %}
                {{ form_rest(form) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{{'cancel'|trans({}, 'agenda') }}</button>
                <button type="submit" class="btn btn-primary">{{ 'update'|trans({}, 'agenda') }}</button>

                <a class="btn btn-danger delete-event" href="
                    {% if isGuest is defined %}
                        {{ path('claro_agenda_delete_guest_event', {'event': event.getId()}) }}
                    {% else %}
                        {{ path('claro_agenda_delete_event', {'event': event.getId()}) }}
                    {% endif %}
                    "
                   data-dismiss="modal">
                    {{ 'delete'|trans({}, 'platform') }}
                </a>
            </div>
        </form>
    </div>
</div>